# name of the workflow, what it is doing (optional)
name: CI CPU testing

# events that trigger the workflow (required)
on:
  push:
    branches: [master, CIdebug]
  pull_request:
    # pull request where master is target
    branches: [master]

# the workflow that gets triggerd
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]  # Error: Container action is only supported on Linux
        python-version: [3.9]
        model: ['yolov8n']  # models to test

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 50
    steps:
      # Check out the repository recursively, updated to v3
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Prepare environment with python 3.9
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # If not importing this prior to installing requirements...
          # ImportError: lap requires numpy, please "pip install numpy". Workaround...
          pip install numpy
          pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
          pip install requests
          python --version
          pip --version
          pip list
        shell: bash
      - name: Tests all tracking options
        run: |
          # deepocsort
          python track.py --tracking-method deepocsort --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg

          # botsort
          python track.py --tracking-method botsort --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          
          # strongsort
          python track.py --tracking-method strongsort --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          
          # ocsort
          python track.py --tracking-method ocsort --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          
          # bytetrack
          python track.py --tracking-method bytetrack --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          
      - name: Tests tracker with exported reid model
        shell: bash  # for Windows compatibility
        run: |
          # export
          python trackers/deep/reid_export.py --weights weights/mobilenetv2_x1_4_dukemtmcreid.pt  # export deafults to torchscript
          
          # strongsort w. exported reid model
          python track.py --reid-model weights/mobilenetv2_x1_4_dukemtmcreid.torchscript --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
      
      - name: Test tracking with seg models
        shell: bash  # for Windows compatibility
        run: |
          # tracking with SEG models
          python track.py --tracking-method deepocsort --yolo-model yolov8n-seg.pt --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg

      - name: Test tracking with pose models
        shell: bash  # for Windows compatibility
        run: |
          # tracking with POSE models
          python3 track.py --yolo-model yolov8n-pose.pt --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg

      - name: Test validation on MOT17 subset
        shell: bash  # for Windows compatibility
        run: |
          # validation on a few MOT17 imges
          python val.py --tracking-method deepocsort --yolo-model yolov8n.pt --benchmark MOT17-mini

      - name: Test evolution on MOT17 subset
        shell: bash  # for Windows compatibility
        run: |
          # evolve a for a single set of parameters
          python evolve.py --objectives HOTA,MOTA,IDF1 --benchmark MOT17-mini --n-trials 1
